apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamac-backend
  namespace: default
  labels:
    app: jamac-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jamac-backend
  template:
    metadata:
      labels:
        app: jamac-backend
    spec:
      hostNetwork: true
      containers:
      - name: jamac-backend
        image: ghcr.io/tony007-infor/jamac-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-env
        # Opcional: Recursos recomendados para producción
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
