apiVersion: v1
kind: Service
metadata:
  name: jamac-backend-service
  namespace: default
  labels:
    app: jamac-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: jamac-backend
